# Site
repository: sudiphdata22/sudiphore.github.io
favicon: assets/img/favicon.ico

# Content settings
lang: en
icon: ⚛️
hide_social: false

# Header
navbar_fixed: true
footer_fixed: true

# Site settings
title: Sudip Hore
first_name: Sudip
last_name: Hore
email: sudip22.official@gmail.com
description: >
  Data Engineer | Databricks • PySpark • Python • Spark SQL • ADF • Data Warehouse
baseurl: ""
url: "https://sudiphdata22.github.io"
last_updated: true

# Social integration
twitter_username: 
github_username: sudiphdata22
linkedin_username: www.linkedin.com/in/sudip2
instagram_username: 

# Build settings
markdown: kramdown
remote_theme: alshedivat/al-folio
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-email-obfuscate
  - jemoji

# Pagination
pagination:
  enabled: true
  per_page: 8
  permalink: /blog/page/:num/
  sort_field: date
  sort_reverse: true

# Exclude
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - _site/

# Other settings
mask_email: false
